package bus

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

// buildArtifactDirs names the regenerable build output PurgeBuildArtifacts may
// remove.
//
// Deliberately one entry. cdk.out is always pure synth output, always
// gitignored, and always regenerated by the next build, which makes deleting
// it free rather than merely cheap — and it is where the space goes: 34 GB
// across 14 repos when this was written. node_modules costs a network install
// to rebuild; dist and .next vary too much per project to assume.
var buildArtifactDirs = []string{"cdk.out"}

// ArtifactPurgeResult reports what a purge removed.
type ArtifactPurgeResult struct {
	Paths      []string // absolute paths removed (or that would be, when dry run)
	BytesFreed int64
}

// ArtifactPurgeDisabled reports whether automatic purging is switched off.
func ArtifactPurgeDisabled() bool {
	return os.Getenv("MUXCODE_ARTIFACT_PURGE_DISABLE") == "1"
}

// PurgeBuildArtifacts removes regenerable build output from repoDir, returning
// what it freed. A dry run measures without deleting.
//
// Every candidate must be confirmed gitignored by git itself before removal.
// The list above is fixed and known safe, so the check is not there to vet the
// name — it is there so that a repo which has deliberately committed a path
// named cdk.out keeps it. Deleting tracked work to reclaim disk would be a far
// worse failure than staying full.
func PurgeBuildArtifacts(repoDir string, dryRun bool) (*ArtifactPurgeResult, error) {
	result := &ArtifactPurgeResult{}
	if repoDir == "" {
		return result, nil
	}
	for _, name := range buildArtifactDirs {
		path := filepath.Join(repoDir, name)
		info, err := os.Stat(path)
		if err != nil || !info.IsDir() {
			continue
		}
		if !gitIgnores(repoDir, path) {
			continue
		}
		size := dirSize(path)
		if !dryRun {
			if err := os.RemoveAll(path); err != nil {
				return result, err
			}
		}
		result.Paths = append(result.Paths, path)
		result.BytesFreed += size
	}
	return result, nil
}

// PurgeSessionArtifacts purges the session repo's build artifacts, naming the
// occasion in the lifecycle row. Every automatic trigger funnels through here,
// so the opt-out and the "nothing to do" silence are honoured once.
func PurgeSessionArtifacts(session, reason string) *ArtifactPurgeResult {
	if ArtifactPurgeDisabled() {
		return nil
	}
	repoDir := SessionRepoDir(session)
	if repoDir == "" {
		return nil
	}
	result, err := PurgeBuildArtifacts(repoDir, false)
	if err != nil {
		LogLifecycle(session, "warn", "daemon", "artifact-purge-failed",
			fmt.Sprintf("%s: %v", reason, err))
		return result
	}
	if len(result.Paths) == 0 {
		return result
	}
	LogLifecycle(session, "info", "daemon", "artifact-purge",
		fmt.Sprintf("%s: freed %s (%s)", reason, formatBytes(result.BytesFreed),
			strings.Join(result.Paths, ", ")))
	return result
}

// gitIgnores reports whether git considers path ignored in repoDir.
func gitIgnores(repoDir, path string) bool {
	cmd := exec.Command("git", "-C", repoDir, "check-ignore", "-q", path)
	return cmd.Run() == nil
}
